- hosts: all
  gather_facts: false
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  
    - include: tasks/main.yml
